apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: service-catalog
  namespace: desire6g-smo
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32006
  selector:
    run: service-catalog
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service-catalog
  name: service-catalog
  namespace: desire6g-smo
spec:
  containers:
  - image: d6g-smo.netcom.it.uc3m.es/desire6g/desire6g-service-catalog:latest
    name: service-catalog
    ports:
    - containerPort: 8000
    resources: {}
    imagePullPolicy: Always
    env:
      - name: GITHUB_ORG
        value: nubispc
      - name: GITHUB_REPO
        value: d6g-sc-store
      - name: GITHUB_ACCESS_TOKEN
        value: <SECRET>
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
