apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: desire6g-service-catalog
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: desire6g-service-catalog
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: desire6g-service-catalog
  name: desire6g-service-catalog
spec:
  containers:
  - image: harbor.nbfc.io/desire6g/desire6g-service-catalog
    name: desire6g-service-catalog
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
